services:
  data_lake_db:
    image: redis
    ports:
      - '6379:6379'
    command: >
      --requirepass pass
    environment:
      REDIS_PASSWORD: 'pass'

  warehouse_db:
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_DATABASE: 'it_jobs_meta_datawarehouse'
      MYSQL_USER: 'it_jobs_meta_worker'
      MYSQL_PASSWORD: 'userpass'


  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'example'
