#!/usr/bin/env bash

set -euo pipefail

function set_swap {
    sudo dd if=/dev/zero of=/swapfile bs=128M count=8
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    sudo tee -a /etc/fstab <<< '/swapfile swap swap defaults 0 0'
    sudo sysctl vm.swappiness=1
}

function install_deps {
    sudo apt update -y
    sudo apt upgrade -y
    sudo apt install -y \
        docker \
        docker-compose
}

function setup_docker {
    sudo usermod -aG docker $USER
    newgrp docker
}

function install_python3.10 {
    sudo add-apt-repository -y ppa:deadsnakes/ppa
    sudo apt install -y python3.10
    sudo apt install -y python3.10-distutils
}

function install_pip3.10 {
    curl -sS 'https://bootstrap.pypa.io/get-pip.py' | python3.10
}

function install_app {
    python3.10 -m pip install build virtualenv
    python3.10 -m build
    python3.10 -m pip install dist/it_jobs_meta*.whl
}

set_swap
install_deps
install_python3.10
install_pip3.10
install_app
setup_docker
