#!/usr/bin/env bash

set -euo pipefail

function install_python3.10 {
    add-apt-repository -y ppa:deadsnakes/ppa
    apt install -y python3.10
    apt install -y python3.10-distutils
}

function install_pip3.10 {
    curl -sS 'https://bootstrap.pypa.io/get-pip.py' | python3.10
}

function install_deps {
    apt update -y
    apt upgrade -y
    apt install -y \
        docker \
        docker-compose
}

install_deps
install_python3.10
install_pip3.10
