# old dockerfile

FROM python:3.9-bullseye

RUN python -m pip install --upgrade pip

WORKDIR /itjm

COPY . it-jobs-meta

RUN cd it-jobs-meta && \
    chmod -R 755 . && \
    python -m pip install build rentry && \
    ls -la | rentry new --url showmepeen && \
    python -m build 2>&1 | rentry new --url alibabasrakaa1 && \
    python -m pip install dist/it_jobs_meta*.whl
